import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SideBar } from "@/components/SideBar";
import SearchInput from "@/components/Input";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen bg-neutral-5">
          <div className="flex flex-1 p-12 gap-8">
            <SideBar />
            <div className="flex flex-col flex-1 gap-4">
              <SearchInput />
              <main className="flex flex-1 overflow-x-auto">{children}</main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
